### ISSUE TITLE
What I have to do if I print header and footer of my print content

### ISSUE THREAD

**Issue by shamim4063** [gilf/ngPrint#10]
I have to print a html table which created anularjs ng-repeat where have lots of data. So it require more than one page. Now I have to attach a header and a footer in every printing page? How to do it, Please explain????

**Comment by gilf** [comment]
You should create a print media query in your CSS and style the elements you want to print inside of it (there is an example of print media query in ngPrint.css file).
This can be very cumbersome but that is the only way. 

P.S. - using a ng-repeat on a big data source is something that you would like to avoid due to performance problems that it causes. Use paging/infinite or virtual scrolling instead if you can.

**Comment by shamim4063** [comment]
Thanks sir I will try accordingly....................

Sincerely
MD. Shamim Hossain
Bangladesh
